language:  go
go:
  - "1.11.1"
go_import_path:	v.io/x/lib
install:
  - go get -t v.io/...
script:
  - go test ./...
notifications:
  email:
    receipients:
      - vanadium-ci@v.io
    on_success: never
    on_failure: always
