sudo: false
dist: trusty
language: go
go:
- 1.11.4
go_import_path: v.io/x/lib
install:
- go get v.io/...
script:
- go test --tags=travis ./...
notifications:
  email:
    receipients:
    - vanadium-ci@v.io
    on_success: never
    on_failure: always
env:
  global:
    - GO111MODULE=on
    - secure: OYevMgak+N2Zabub+3vmv2pq6vgNBFzFgMR4R7DF19jX8JDJt3eN58RAwuz2Vm5KRBP2aI7jDWF3f9mvkNW6/Dv/4Bp64HtdwWJjrny1cDrdYb8hZvhC63zNsHI7rQMtnqj61B5HtRNKEgzootc4giJ4HCaVGSAXdwkSUtzuwwsHhnpUp/gLOEIeBDmR1nhS9Wtl9hqpQ23bgsop0Ym2YjixGiZTiC+KjN3m/wUbqIZXBvbM1Ygtv3Hd07ngk1KOnxEHsAlZ26bv39mS2c5zNC3leLthMjZrlTw4dS8ge4MI9fK2Pf/SXDHAFsKMH5pYOipSJl7H7zpHlUHCk0CrDyR49K+nIWpYs76NMNhANnyRltumKq9HQl+42UjMbS+QZMu+Rh7RwSwE108H9L1SE+HzXC9paREbKv0vKfxqP17xK81C0mkDQ6B8XttuQbJsin0c/+5+uIzy3DBgVUkpguF2AyWwSb7cNsRVeui4i1ZmM9UFxnpL0mT021tNGzBmu8/w3qEjTiSsBBREvqtpIVXGdq0HdALE3QK72b1ls1ZSIMT6Wrotk30fJFlhh/SBTqvC2Whh5sPOO26vCllihedS+7wSpJ4HEAgmJc6okv4gKwwZgthVr+iJU75CJLuG9vpLAs8G7EWyc1tdHEZTPSTAh5InoVGCbTNGrCy+/14=
after_success:
- bash ./trigger-travis-build.sh $TRAVIS_API_TOKEN vanadium core
