name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: github.com/vanadium/go.lib

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: github.com/vanadium/go.lib/go.sum

      - name: Test
        run: |
          cd github.com/vanadium/go.lib
          go test --race --covermode=atomic ./...

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: github.com/vanadium/go.lib

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true
          cache-dependency-path: github.com/vanadium/go.lib/go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: github.com/vanadium/go.lib

      - name: Vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          cd github.com/vanadium/go.lib && govulncheck ./...
