name: macos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: v.io/vanadium/x/ref/lib

      - name: Test
        run: |
          cd v.io/x/ref/lib
          go test -failfast --covermode=atomic -race ./...
