name: windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: github.com/vanadium/go.lib

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ./go.sum

      - name: Test
        run: |
          which go
          echo "path $PATH"
          go test --race --covermode=atomic ./...
