name: windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ./go.sum

      - name: env
        run: |
          echo 1; which go echo
          echo 2; echo $PATH
          echo 3; echo $GOBIN
          echo 4; go version
          echo 5; pwd

      - name: Test
        run: |
          which go
          go test --race --covermode=atomic ./...
